#!/bin/bash

# Source virtualenvwrapper, added by pydata.sh

export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

export WORKON_HOME=~/dev/VirtualEnvs
export PROJECT_HOME=~/dev/hacking

export PIP_REQUIRE_VIRTUALENV=true
source /usr/local/bin/virtualenvwrapper.sh

gpip() {
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
gpip2() {
    PIP_REQUIRE_VIRTUALENV="" pip2 "$@"
}
