#!/bin/bash

source /usr/local/bin/virtualenvwrapper.sh

export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

export WORKON_HOME=~/dev/VirtualEnvs
export PROJECT_HOME=~/dev

export PIP_REQUIRE_VIRTUALENV=true

gpip() {
    PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}
gpip2() {
    PIP_REQUIRE_VIRTUALENV="" pip2 "$@"
}
